---
# Copyright (C) 2014 Matthew Cengia
- hosts: ryan.cengia.id.au
  user: root
  vars:
    motd_warning: "WARNING: You are connected to {{ansible_fqdn}}. Unauthorised access is prohibited!\n"
    allowed_inbound_ports:
      - ssh
      - smtp
    relayhost: "[cengia.id.au]:1025"
    relay_domains: "cengia.id.au"
  roles:
    - common
    - postfix_relay
