---
- hosts: ryan.cengia.id.au
  user: root
  vars:
    motd_warning: "WARNING: You are connected to ryan.cengia.id.au. Unauthorised access is prohibited!\n"

  tasks:

#    - name: etckeeper pre-commit
#      command: etckeeper commit "Pre-Ansible Changes"

    - name: setup a MOTD
      copy:
        dest: /etc/motd
        content: "{{ motd_warning }}"

    - name: Update APT package cache
      apt: update_cache=yes

    #- name: Upgrade APT to the lastest packages
    #  apt: upgrade=safe

    - name: Install python-augeas
      apt: pkg=python-augeas state=latest

    # Firewall

    - name: install iptables-persistent
      apt: pkg=iptables-persistent state=latest

    - name: create firwall config dir
      file: path=/etc/iptables state=directory mode=0755 owner=root
      notify: etckeeper post-commit

    - name: copy in ipv4 firewall rule files
      action: copy src=ryan-files/rules.v4 dest=/etc/iptables/rules.v4 mode=0744
      notify:
        - restart iptables-persistent
        - etckeeper post-commit

    - name: copy in ipv6 firewall rule files
      action: copy src=ryan-files/rules.v6 dest=/etc/iptables/rules.v6 mode=0744
      notify:
        - restart iptables-persistent
        - etckeeper post-commit

    # SSH

    - name: Lock down SSH
      augeas: command="set" path="/files/etc/ssh/sshd_config/PermitRootLogin" value="without-password"
      notify: restart openssh-server


  handlers:

    - name: restart iptables-persistent
      service:
        name: iptables-persistent
        state: restarted

    - name: restart openssh-server
      service:
        name: openssh-sever
        state: restarted

    - name: etckeeper post-commit
      command: etckeeper commit "Post-Ansible Changes"

# sudo augtool -s set /files/etc/postfix/main.cf/relayhost '[cengia.id.au]:1025'
# ( x=$(augtool match /files/etc/hosts/\*/ipaddr 127.0.0.1); sudo augtool -s set "${x%/*}"/canonical localhost.localdomain; sudo augtool -s set "${x%/*}"/alias localhost; )
# sudo augtool -s set /files/etc/postfix/main.cf/relay_domains cengia.id.au
# sudo augtool -s set /files/etc/postfix/main.cf/mydestination "'ryan.cengia.id.au, localhost.localdomain, localhost'"
# sudo augtool -s set /files/etc/postfix/main.cf/recipient_delimiter -
