---
- hosts: ryan.cengia.id.au
  user: root
  vars:
    motd_warning: "WARNING: You are connected to ryan.cengia.id.au. Unauthorised access is prohibited!\n"
  tasks:
    - name: setup a MOTD
      copy:
        dest: /etc/motd
        content: "{{ motd_warning }}"

    - name: install iptables-persistent
      apt: pkg=iptables-persistent state=latest
    - name: create firwall config dir
      file: path=/etc/iptables state=directory mode=0755 owner=root
    - name: copy in ipv4 firewall rule files
      action: copy src=ryan-files/rules.v4 dest=/etc/iptables/rules.v4 mode=0744
      notify:
        - restart iptables-persistent
        - etckeeper post-commit
    - name: copy in ipv6 firewall rule files
      action: copy src=ryan-files/rules.v6 dest=/etc/iptables/rules.v6 mode=0744
      notify:
        - restart iptables-persistent

  handlers:
    - name: restart iptables-persistent
      service:
        name: iptables-persistent
        state: restarted

    - name: install postfix
      apt: pkg=postfix state=latest
