---
# Copyright (C) 2014 Matthew Cengia
- hosts: sonar.cyber
  user: root
  vars:
    motd_warning: "WARNING: You are connected to {{ansible_fqdn}}. Unauthorised access is prohibited!\n"
    allowed_inbound_ports:
      - ssh
  roles:
    - common
